#!/usr/bin/env python3

import argparse
from pathlib import Path


DEFAULT_MAX_PAIRS = 64


def comma_join(items):
    return ", ".join(items)


def pair_params(pair_count):
    params = []
    for i in range(pair_count):
        params.extend((f"t{i}", f"n{i}"))
    return comma_join(params)


def pair_macro_body(pair_count, separator, terminator=""):
    body = separator.join(f"macro(t{i}, n{i})" for i in range(pair_count))
    return f"{body}{terminator}"


def render_count_args(max_args):
    count_values = comma_join(str(i) for i in range(max_args, -1, -1))
    count_params = comma_join(f"_{i}" for i in range(1, max_args + 1))
    return (
        f"#define COUNT_ARGS(...) COUNT_ARGS_IMPL(__VA_ARGS__ __VA_OPT__(,) {count_values})\n"
        f"#define COUNT_ARGS_IMPL({count_params}, N, ...) N"
    )


def render_for_each_block(name, max_pairs, separator, terminator=""):
    max_args = max_pairs * 2
    lines = [
        f"// Implement {name}_N for different argument counts "
        f"(0 to {max_pairs} parameter pairs = 0 to {max_args} arguments)",
        f"#define {name}_0(macro, ...)",
        "",
    ]

    for arg_count in range(2, max_args + 1, 2):
        pair_count = arg_count // 2
        lines.append(f"#define {name}_{arg_count}(macro, {pair_params(pair_count)}) \\")
        lines.append(f"    {pair_macro_body(pair_count, separator, terminator)}")

    return "\n".join(lines)


def render_header(max_pairs):
    max_args = max_pairs * 2
    return f"""#pragma once

// Generated by xsched/utils/tools/gen_function_h.py --max-pairs {max_pairs}.
// Supports up to {max_pairs} parameter pairs ({max_args} macro arguments).

#include "xsched/utils/log.h"
#include "xsched/utils/common.h"
#include "xsched/utils/xassert.h"

// Helper macros to count arguments
{render_count_args(max_args)}

// Helper macro to concatenate
#define CONCAT(a, b) CONCAT_IMPL(a, b)
#define CONCAT_IMPL(a, b) a##b

// Helper macros to handle function parameters and types
#define DECLARE_PARAM(type, name) type name
#define DECLARE_TYPE(type, name) type
#define DECLARE_ARG(type, name) name
#define DECLARE_PRIVATE_PARAM(type, name) type name##_
#define DECLARE_PRIVATE_ARG(type, name) name##_
#define DECLARE_COPY_PRIVATE_ARG(type, name) name##_(name)

// Save the address in the macro and call the function
#define DEFINE_ADDRESS_CALL_WITH_PREFIX(prefix, addr, ret_t, func, ...)            \\
    prefix ret_t func(FOR_EACH_PAIR_COMMA(DECLARE_PARAM, __VA_ARGS__)) {{           \\
        using FuncPtr = ret_t (*)(FOR_EACH_PAIR_COMMA(DECLARE_TYPE, __VA_ARGS__)); \\
        static const auto func_ptr = reinterpret_cast<FuncPtr>(addr);              \\
        XDEBG("call "#func"() @ %p", func_ptr);                                    \\
        return func_ptr(FOR_EACH_PAIR_COMMA(DECLARE_ARG, __VA_ARGS__));            \\
    }}

// Directly call the target function
#define DEFINE_REDIRECT_CALL_WITH_PREFIX(prefix, target, ret_t, func, ...) \\
    prefix ret_t func(FOR_EACH_PAIR_COMMA(DECLARE_PARAM, __VA_ARGS__)) {{   \\
        XDEBG("redirect "#func"() -> "#target"()");                        \\
        return target(FOR_EACH_PAIR_COMMA(DECLARE_ARG, __VA_ARGS__));      \\
    }}

// Check the ptr and directly call the target function
#define DEFINE_REDIRECT_ADDRESS_CALL_WITH_PREFIX(prefix, target_ptr, ret_t, func, ...) \\
    prefix ret_t func(FOR_EACH_PAIR_COMMA(DECLARE_PARAM, __VA_ARGS__)) {{               \\
        XASSERT(target_ptr != nullptr, "target_ptr is nullptr");                       \\
        XDEBG("redirect "#func"() -> %p", target_ptr);                                 \\
        return target_ptr(FOR_EACH_PAIR_COMMA(DECLARE_ARG, __VA_ARGS__));              \\
    }}

#define DEFINE_STATIC_ADDRESS_CALL(addr, ret_t, func, ...)      \\
    DEFINE_ADDRESS_CALL_WITH_PREFIX(static, addr, ret_t, func, __VA_ARGS__)

#define DEFINE_STATIC_REDIRECT_CALL(target, ret_t, func, ...)   \\
    DEFINE_REDIRECT_CALL_WITH_PREFIX(static, target, ret_t, func, __VA_ARGS__)

#define DEFINE_STATIC_ADDRESS_REDIRECT_CALL(target_ptr, ret_t, func, ...)   \\
    DEFINE_REDIRECT_ADDRESS_CALL_WITH_PREFIX(static, target_ptr, ret_t, func, __VA_ARGS__)

#define DEFINE_C_REDIRECT_CALL(target, ret_t, func, ...)        \\
    DEFINE_REDIRECT_CALL_WITH_PREFIX(extern "C", target, ret_t, func, __VA_ARGS__)

#define DEFINE_EXPORT_C_REDIRECT_CALL(target, ret_t, func, ...) \\
    DEFINE_REDIRECT_CALL_WITH_PREFIX(EXPORT_C_FUNC, target, ret_t, func, __VA_ARGS__)

#define DEFINE_EXPORT_CXX_REDIRECT_CALL(target, ret_t, func, ...) \\
    DEFINE_REDIRECT_CALL_WITH_PREFIX(EXPORT_CXX_FUNC, target, ret_t, func, __VA_ARGS__)

// FOR_EACH_PAIR_COMMA implementation for handling parameter pairs
#define FOR_EACH_PAIR_COMMA(macro, ...) \\
    CONCAT(FOR_EACH_PAIR_COMMA_, COUNT_ARGS(__VA_ARGS__))(macro, __VA_ARGS__)

// FOR_EACH_PAIR_SEMICOLON implementation for defining parameter pairs
#define FOR_EACH_PAIR_SEMICOLON(macro, ...) \\
    CONCAT(FOR_EACH_PAIR_SEMICOLON_, COUNT_ARGS(__VA_ARGS__))(macro, __VA_ARGS__)

{render_for_each_block("FOR_EACH_PAIR_COMMA", max_pairs, ", ")}

{render_for_each_block("FOR_EACH_PAIR_SEMICOLON", max_pairs, "; ", ";")}
"""


def parse_args():
    script_dir = Path(__file__).resolve().parent
    default_output = script_dir.parent / "include" / "xsched" / "utils" / "function.h"

    parser = argparse.ArgumentParser(
        description="Generate xsched/utils/include/xsched/utils/function.h."
    )
    parser.add_argument(
        "--max-pairs",
        type=int,
        default=DEFAULT_MAX_PAIRS,
        help=f"maximum number of (type, name) parameter pairs, default: {DEFAULT_MAX_PAIRS}",
    )
    parser.add_argument(
        "-o",
        "--output",
        type=Path,
        default=default_output,
        help=f"output path, default: {default_output}",
    )
    return parser.parse_args()


def main():
    args = parse_args()
    if args.max_pairs < 0:
        raise SystemExit("--max-pairs must be non-negative")

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(render_header(args.max_pairs), encoding="utf-8")


if __name__ == "__main__":
    main()
